package views;

import java.awt.*;
import java.net.URL;
import javax.swing.*;

public class inicio extends javax.swing.JFrame {
    
    public inicio() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
           setSize(1366, 770);  // O usa pack() si prefieres auto-ajuste
           // Cargar y agregar JLabel como fondo
           URL imagenURL = getClass().getResource("/1.png");  // Desde src/main/resources
           if (imagenURL != null) {
               ImageIcon iconoOriginal = new ImageIcon(imagenURL);
               // Escala la imagen al tamaño del JFrame
               Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(
                   getWidth(), getHeight(), Image.SCALE_SMOOTH);
               JLabel labelFondo = new JLabel(new ImageIcon(imagenEscalada));
               
               // Posiciona el JLabel para cubrir todo el JFrame
               labelFondo.setBounds(0, 0, 1366, 770);
               
               // Agrega el JLabel al final para que esté "debajo" de otros componentes
               add(labelFondo);
               
               // Si usas layout absoluto, asegúrate de que otros componentes se superpongan
               setLayout(null);  // O ajusta según tu layout actual
               
               // Ejemplo: Reposiciona un botón existente (si lo tienes del Designer)
               // jButton1.setBounds(100, 100, 100, 30);
           } else {
               System.err.println("Error: Imagen no encontrada en resources");
           }
           setVisible(true);
           }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\jimem\\OneDrive\\Documentos\\NetBeansProjects\\venta_boletos\\src\\main\\resources\\images\\1.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    
    public static void main(String args[]) {
java.awt.EventQueue.invokeLater(() -> new inicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
