package views;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Image;
import java.util.HashSet;
import java.util.Set;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import services.usuario_service;
import models.usuario_model;

import javax.swing.*;

public class Register extends javax.swing.JFrame {
    private inicio back;
    private JList<String> listBox;
    private DefaultListModel<String> listModel;
    
    private final usuario_service service = new usuario_service();  
    public Register() {
        initComponents();
        
        this.setLocationRelativeTo(this);
        this.Imagen(this.lblfondo, "src/main/resources/images/3.png");
    
    listModel = new DefaultListModel<>();
    listModel.addElement("Administrador");
    listModel.addElement("Vendedor");
    
    jlistRol.setModel(listModel);
    }
    
    private ImageIcon imagen;
    private Icon icono;

    public void setBack(inicio back) {
        this.back = back;
    }
    

    
    
    /* 
*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pfondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblRol = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtContra = new javax.swing.JTextField();
        btnRegreso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistRol = new javax.swing.JList<>();
        txtName = new javax.swing.JTextField();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pfondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(4, 36, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrate");
        pfondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setText("Nombre:");
        pfondo.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        pfondo.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 200, 30));

        lblRol.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRol.setForeground(new java.awt.Color(0, 0, 0));
        lblRol.setText("Rol:");
        pfondo.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, -1, -1));

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(0, 0, 0));
        lblUser.setText("Usuario:");
        pfondo.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 70, -1));

        btnCrear.setBackground(new java.awt.Color(4, 36, 51));
        btnCrear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear");
        btnCrear.setToolTipText("");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        pfondo.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 120, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Contraseña:");
        pfondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 110, 20));

        txtContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraActionPerformed(evt);
            }
        });
        pfondo.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 200, 30));

        btnRegreso.setBackground(new java.awt.Color(0, 0, 0));
        btnRegreso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegreso.setForeground(new java.awt.Color(255, 255, 255));
        btnRegreso.setText("Regreso");
        btnRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresoActionPerformed(evt);
            }
        });
        pfondo.add(btnRegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, -1, -1));

        jScrollPane1.setViewportView(jlistRol);

        pfondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 130, 20));
        pfondo.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 200, 30));
        pfondo.add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1150, 630));

        getContentPane().add(pfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
    try {
        String nombre = txtName.getText();
        String user = txtName.getText();
        String contrasenia = txtContra.getText();
        String rol = jlistRol.getSelectedValue();
        
        if (nombre.isEmpty() || user.isEmpty()){
            JOptionPane.showMessageDialog(this, "Todos los campos deben ser llenados");
            return;
        }
        if(rol == null){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un rol");
            return;
        }
        if(contrasenia.length() < 6){
            JOptionPane.showMessageDialog(this, "La contrasenia debe tener al menos 6 caracteres");
            return;
        }
        
        usuario_model newUser = new usuario_model();
        newUser.setNombre_completo(nombre);
        newUser.setNombre_usuario(user);
        newUser.setContrasena(contrasenia);
        newUser.setRol(rol);
        
        service.createUser(newUser);
        
        JOptionPane.showMessageDialog(this, "Usuario registrado correctamente");
        
        cleanFields();
    }catch(Exception ex){
        JOptionPane.showMessageDialog(this, "Error al registrar el usuario");
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresoActionPerformed
        back.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresoActionPerformed

    /**
     * @param args the command line arguments
     */

        private void cleanFields(){
        txtName.setText("");
        txtUser.setText("");
        txtContra.setText("");
    }    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    private void Imagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(lbl.getWidth(), 
                        lbl.getHeight(), 
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnRegreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlistRol;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JPanel pfondo;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}